# To generate slyde.gif, run:
#
#   cargo build --release
#   vhs slyde.tape

Output slyde.gif

Set Height 700

Type "target/release/slyde --demo"
Enter

Type "s"
Sleep 0.35s
Type "d"
Sleep 0.35s
Type "d"
Sleep 0.35s
Type "w"
Sleep 0.35s
Type "a"
Sleep 0.35s
Type "a"
Sleep 0.35s
Type "a"
Sleep 0.35s
Type "s"
Sleep 0.35s
Type "d"
Sleep 0.35s
Type "d"
Sleep 0.35s
Type "d"
Sleep 0.35s
Type "w"
Sleep 0.35s
Type "a"
Sleep 0.35s
Type "a"
Sleep 0.35s
Type "a"
Sleep 0.35s



Sleep 2s
Type "q"
